// Generates per-post AI metadata (TL;DR + bespoke suggested questions) by
// asking Node's own worker, and writes it to src/data/aiMeta.ts so visitors
// get it for free — no runtime LLM calls, no per-visitor cost.
//
// Run manually after adding content:  npx tsx scripts/generate-ai-meta.ts
import { writeFileSync } from "node:fs";
import { mediumPosts } from "../src/data/medium";
import { notes } from "../src/data/notes";
import { posts } from "../src/data/posts";

const WORKER_URL = process.env.VITE_NODE_PROXY_URL ?? "https://rameez-node-proxy.rxmeez.workers.dev";

interface AiMeta {
  tldr: string;
  questions: string[];
}

function stripHtml(html: string): string {
  return html
    .replace(/<pre[\s\S]*?<\/pre>/g, " [code block] ")
    .replace(/<[^>]*>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

async function readSseAnswer(response: Response): Promise<string> {
  const text = await response.text();
  if (!text.startsWith("data:") && !text.includes("\ndata:")) {
    // Non-streaming JSON body
    try {
      const data = JSON.parse(text) as { choices?: { message?: { content?: string } }[] };
      return data.choices?.[0]?.message?.content ?? "";
    } catch {
      return text;
    }
  }
  let answer = "";
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("data: ") || trimmed === "data: [DONE]") continue;
    try {
      const data = JSON.parse(trimmed.slice(6)) as { choices?: { delta?: { content?: string } }[] };
      answer += data.choices?.[0]?.delta?.content ?? "";
    } catch {}
  }
  return answer;
}

function parseMeta(raw: string): AiMeta | null {
  const match = raw.match(/\{[\s\S]*\}/);
  if (!match) return null;
  try {
    const data = JSON.parse(match[0]) as Partial<AiMeta>;
    if (typeof data.tldr !== "string" || !Array.isArray(data.questions)) return null;
    const questions = data.questions.filter((q): q is string => typeof q === "string").slice(0, 3);
    if (!data.tldr.trim() || questions.length < 2) return null;
    return { tldr: data.tldr.trim(), questions };
  } catch {
    return null;
  }
}

async function generateFor(title: string, content: string, type: string): Promise<AiMeta | null> {
  const question = `Ignore your usual formatting rules. You are generating metadata for the ${type} the user is reading. Reply with ONLY a valid JSON object, no markdown fences, no other text, in exactly this shape: {"tldr": "...", "questions": ["...", "...", "..."]}. The tldr is a crisp 1-2 sentence summary of this specific ${type}. The questions are three short (under 9 words), specific questions a curious reader would actually ask about this ${type}'s content — not generic ones.`;

  for (let attempt = 0; attempt < 3; attempt++) {
    const response = await fetch(WORKER_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json", Origin: "https://rameez.co" },
      body: JSON.stringify({
        question,
        pageContext: { title, content: stripHtml(content).slice(0, 6000), type },
      }),
    });
    if (!response.ok) {
      console.error(`  attempt ${attempt + 1}: HTTP ${response.status}`);
      continue;
    }
    const answer = await readSseAnswer(response);
    const meta = parseMeta(answer);
    if (meta) return meta;
    console.error(`  attempt ${attempt + 1}: unparseable reply: ${answer.slice(0, 120)}`);
  }
  return null;
}

async function main() {
  const items = [
    ...posts.map((p) => ({ slug: p.slug, title: p.title, content: p.content, type: "post" })),
    ...mediumPosts.map((p) => ({ slug: p.slug, title: p.title, content: p.content, type: "post" })),
    ...notes.map((n) => ({ slug: n.slug, title: n.title, content: n.content, type: "note" })),
  ];

  const meta: Record<string, AiMeta> = {};
  for (const item of items) {
    console.log(`Generating: ${item.title}`);
    const result = await generateFor(item.title, item.content, item.type);
    if (result) {
      meta[item.slug] = result;
      console.log(`  ✓ ${result.tldr.slice(0, 70)}...`);
    } else {
      console.error(`  ✗ skipped ${item.slug}`);
    }
  }

  const file = `// AUTO-GENERATED by scripts/generate-ai-meta.ts — do not edit by hand.
// Regenerate after adding content:  npx tsx scripts/generate-ai-meta.ts

export interface AiMeta {
  tldr: string;
  questions: string[];
}

export const aiMeta: Record<string, AiMeta> = ${JSON.stringify(meta, null, 2)};
`;
  writeFileSync("src/data/aiMeta.ts", file);
  console.log(`\nWrote src/data/aiMeta.ts (${Object.keys(meta).length}/${items.length} items)`);
}

main();
