// AUTO-GENERATED by scripts/generate-ai-meta.ts — do not edit by hand.
// Regenerate after adding content:  npx tsx scripts/generate-ai-meta.ts

export interface AiMeta {
  tldr: string;
  questions: string[];
}

export const aiMeta: Record<string, AiMeta> = {
  "first-value-last-value-bigquery": {
    "tldr": "FIRST_VALUE and LAST_VALUE in BigQuery behave unexpectedly due to default window frames; always specify an explicit frame clause for LAST_VALUE to get the partition's last value.",
    "questions": [
      "What is the default frame for LAST_VALUE?",
      "Why does LAST_VALUE return the current row?",
      "What alternative to LAST_VALUE works in BigQuery?"
    ]
  },
  "dbt-unit-tests-macros": {
    "tldr": "dbt 1.8's native unit tests are most valuable for macros, not just models, catching logic errors before they corrupt data.",
    "questions": [
      "How do you test macros in isolation?",
      "What edge cases should you test?",
      "How to mock input data with given fixtures?"
    ]
  },
  "goose-schema-migration": {
    "tldr": "Goose is a minimal, no-fuss database migration tool written in Go that works with plain SQL files, supports multiple databases, and offers features like embedded migrations and transaction safety.",
    "questions": [
      "How do you create a migration with Goose?",
      "What databases does Goose support?",
      "Can you write migrations in Go instead of SQL?"
    ]
  },
  "go-error-handling": {
    "tldr": "Go treats errors as values implementing the error interface, with patterns like sentinel errors, wrapping, and custom types; explicit handling forces thinking about failures at every step.",
    "questions": [
      "What is the error interface in Go?",
      "How do you wrap errors with fmt.Errorf?",
      "When should you use errors.Is vs errors.As?"
    ]
  },
  "goose-migrations-quickref": {
    "tldr": "Goose is a Go database migration tool that uses plain SQL files for schema changes, runs in transactions by default, and supports PostgreSQL, MySQL, SQLite, and SQL Server with optional embedding into Go binaries.",
    "questions": [
      "How do I create a new migration with Goose?",
      "Which databases does Goose support?",
      "Can migrations be embedded into a Go binary?"
    ]
  },
  "dbt-unit-test-macros": {
    "tldr": "dbt 1.8 introduced native unit tests; this note shows how to test macros in isolation using fixtures and edge cases, with a concrete example of normalizing email addresses.",
    "questions": [
      "What makes macro testing more valuable than model testing?",
      "How do you mock input data for a macro test?",
      "What edge cases should macro unit tests cover?"
    ]
  }
};
